services:
  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: krekonApiPasswordOskarWasHere123
    image: mongo:latest
    restart: always
    container_name: krekon-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - krekonapinetwork

  redis:
    image: redis:latest
    container_name: krekon-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - krekonapinetwork

  krekonapi:
    container_name: krekonapi
    environment:
      PORT: 8080
    links:
      - "mongodb:db"
      - "redis"
    networks:
      - krekonapinetwork
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongodb

volumes:
  mongodb_data:
  redis_data:

networks:
  krekonapinetwork:
