services:
  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: krekonApiPasswordOskarWasHere123
    image: mongo:latest
    restart: always
    container_name: krekon-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - krekonapinetwork

  redis:
    image: redis:latest
    container_name: krekon-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - krekonapinetwork

  krekonapi:
    container_name: krekonapi
    links:
      - "mongodb:db"
      - "redis"
    networks:
      - krekonapinetwork
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - redis
      - mongodb
      # metabase:
      #   image: metabase/metabase:v0.53.8.4
      #   container_name: metabase
      #   ports:
      #     - "3001:3001"
      #   environment:
      #     - MB_DB_TYPE=postgres  # Metabase requires a backend DB; we'll use an in-memory DB for simplicity
      #     - MB_DB_DBNAME=metabase
      #     - MB_DB_PORT=5432
      #     - MB_DB_USER=metabase
      #     - MB_DB_PASS=metabase
      #     - MB_DB_HOST=metabase-db
      #   depends_on:
      #     - metabase-db
      #   networks:
      #     - krekonapinetwork

      # metabase-db:
      #   image: postgres:latest
      #   container_name: metabase-db
      #   environment:
      #     - POSTGRES_USER=metabase
      #     - POSTGRES_PASSWORD=metabase
      #     - POSTGRES_DB=metabase
      #   volumes:
      #     - metabase_data:/var/lib/postgresql/data
      #   networks:
      #     - krekonapinetwork

volumes:
  mongodb_data:
  redis_data:
    # metabase_data:

networks:
  krekonapinetwork:
    driver: bridge
