services:
  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: krekonApiPasswordOskarWasHere123
    image: mongo:latest
    restart: always
    container_name: krekon-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - krekonapinetwork

  redis:
    image: redis:latest
    container_name: krekon-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - krekonapinetwork

  krekonapi:
    container_name: krekonapi
    environment:
      PORT: 3000
      API_URL: ""
    links:
      - "mongodb"
      - "redis"
    networks:
      - krekonapinetwork
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - redis
      - mongodb

  metabasedb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=PASWORD
      - POSTGRES_USER=USERNAME
      - POSTGRES_DB=DATABASE
    ports:
      - 5432:5432
    volumes:
      - metabasedb-data:/var/lib/postgresql/data
    networks:
      - krekonapinetwork

  metabase:
    volumes:
      - metabase-data:/metabase-data
    environment:
      # - MB_DB_FILE=/metabase-data/metabase.db
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=USERNAME
      - MB_DB_PASS=PASWORD
      - MB_DB_HOST=postgres
    ports:
      - 3001:3000
    image: metabase/metabase
    restart: always
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on: 
      - metabasedb
    networks:
      - krekonapinetwork

volumes:
  mongodb_data:
  redis_data:
  metabasedb-data:
  metabase-data:

networks:
  krekonapinetwork:
    driver: bridge
